[project]
name = "quote0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv[cli]>=1.1.1",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
    "pillow>=10.0.0",
    "requests>=2.31.0",
]
